# Generated by Django 5.1.3 on 2024-12-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='hai@gmail.com', max_length=254),
        ),
    ]


